all:
  vars:
    ansible_user: "{{ lookup('env', 'ansible_user') }}"
    ansible_password: "{{ lookup('env', 'ansible_password') }}"
    ansible_become_pass: "{{ lookup('env', 'ansible_become_pass') }}"
    ansible_become: True
    ansible_become_method: enable
    ansible_connection: ansible.netcommon.netconf
    ansible_python_interpreter: python
  hosts:
  children:
    nxos:
      hosts:
        nxos101:
      vars:
        ansible_network_os: cisco.nxos.nxos
 