arp-items:
    adminSt: enabled
    inst-items:
        adjLoggingLevel: error
        adminSt: enabled
        allowStaticArpOutsideSubnet: disabled
        arpUnnumSviSwReplication: disabled
        cacheLimit: '174080'
        cacheSyslogRate: '1'
        dom-items:
            Dom-list:
            -   if-items:
                    If-list:
                        adminSt: enabled
                        deleteAdjOnMacDelete: disabled
                        duplicateIpDetectionForUnnumberedSvi: disabled
                        gratuitousHsrpDup: enabled
                        gratuitousRequest: enabled
                        gratuitousUpdate: enabled
                        id: mgmt0
                        localProxyArp: disabled
                        localProxyArpNoHwFlood: disabled
                        proxyArp: disabled
                        timeout: '1500'
                name: management
            -   if-items:
                    If-list:
                        adminSt: enabled
                        deleteAdjOnMacDelete: disabled
                        duplicateIpDetectionForUnnumberedSvi: disabled
                        gratuitousHsrpDup: enabled
                        gratuitousRequest: enabled
                        gratuitousUpdate: enabled
                        id: eth1/100
                        localProxyArp: disabled
                        localProxyArpNoHwFlood: disabled
                        proxyArp: disabled
                        timeout: '1500'
                name: default
        evpn_timeout: '600'
        ipAdjRouteDistance: '250'
        loggingLevel: error
        offListTimeout: '180'
        rarpFabricFwding: disabled
        rarpFabricFwdingRate: '200'
        suppression_timeout: '0'
        timeout: '1500'
