bd-items:
    bd-items:
        BD-list:
        -   BdState: active
            adminSt: active
            bridgeMode: mac
            fabEncap: vlan-20
            fwdCtrl: mdst-flood
            fwdMode: bridge,route
            id: '20'
            mode: CE
            name: twenty
            xConnect: disable
        -   BdState: active
            adminSt: active
            bridgeMode: mac
            fabEncap: vlan-10
            fwdCtrl: mdst-flood
            fwdMode: bridge,route
            id: '10'
            mode: CE
            name: ten
            xConnect: disable
        -   BdState: active
            adminSt: active
            bridgeMode: mac
            fabEncap: vlan-1
            fwdCtrl: mdst-flood
            fwdMode: bridge,route
            id: '1'
            mode: CE
            xConnect: disable
    sysDefaultSVIAutostate: enable
