cdp-items:
    inst-items:
        adminSt: enabled
        devIdType: none
        holdIntvl: '180'
        if-items:
            If-list:
            -   adminSt: enabled
                id: eth1/27
            -   adminSt: enabled
                id: eth1/115
            -   adminSt: enabled
                id: eth1/15
            -   adminSt: enabled
                id: eth1/100
            -   adminSt: enabled
                id: eth1/105
            -   adminSt: enabled
                id: eth1/16
            -   adminSt: enabled
                id: eth1/46
            -   adminSt: enabled
                id: eth1/56
            -   adminSt: enabled
                id: eth1/25
            -   adminSt: enabled
                id: eth1/122
            -   adminSt: enabled
                id: eth1/81
            -   adminSt: enabled
                id: eth1/88
            -   adminSt: enabled
                id: eth1/65
            -   adminSt: enabled
                id: eth1/76
            -   adminSt: enabled
                id: eth1/127
            -   adminSt: enabled
                id: eth1/41
            -   adminSt: enabled
                id: eth1/30
            -   adminSt: enabled
                id: eth1/128
            -   adminSt: enabled
                id: mgmt0
            -   adminSt: enabled
                id: eth1/91
            -   adminSt: enabled
                id: eth1/52
            -   adminSt: enabled
                id: eth1/71
            -   adminSt: enabled
                id: eth1/78
            -   adminSt: enabled
                id: eth1/79
            -   adminSt: enabled
                id: eth1/33
            -   adminSt: enabled
                id: eth1/99
            -   adminSt: enabled
                id: eth1/61
            -   adminSt: enabled
                id: eth1/26
            -   adminSt: enabled
                id: eth1/62
            -   adminSt: enabled
                id: eth1/114
            -   adminSt: enabled
                id: eth1/124
            -   adminSt: enabled
                id: eth1/22
            -   adminSt: enabled
                id: eth1/50
            -   adminSt: enabled
                id: eth1/103
            -   adminSt: enabled
                id: eth1/2
            -   adminSt: enabled
                id: eth1/107
            -   adminSt: enabled
                id: eth1/45
            -   adminSt: enabled
                id: eth1/72
            -   adminSt: enabled
                id: eth1/74
            -   adminSt: enabled
                id: eth1/86
            -   adminSt: enabled
                id: eth1/96
            -   adminSt: enabled
                id: eth1/70
            -   adminSt: enabled
                id: eth1/40
            -   adminSt: enabled
                id: eth1/10
            -   adminSt: enabled
                id: eth1/5
            -   adminSt: enabled
                id: eth1/95
            -   adminSt: enabled
                id: eth1/18
            -   adminSt: enabled
                id: eth1/55
            -   adminSt: enabled
                id: eth1/63
            -   adminSt: enabled
                id: eth1/111
            -   adminSt: enabled
                id: eth1/117
            -   adminSt: enabled
                id: eth1/90
            -   adminSt: enabled
                id: eth1/23
            -   adminSt: enabled
                id: eth1/75
            -   adminSt: enabled
                id: eth1/106
            -   adminSt: enabled
                id: eth1/38
            -   adminSt: enabled
                id: eth1/69
            -   adminSt: enabled
                id: eth1/7
            -   adminSt: enabled
                id: eth1/67
            -   adminSt: enabled
                id: eth1/43
            -   adminSt: enabled
                id: eth1/11
            -   adminSt: enabled
                id: eth1/110
            -   adminSt: enabled
                id: eth1/37
            -   adminSt: enabled
                id: eth1/51
            -   adminSt: enabled
                id: eth1/42
            -   adminSt: enabled
                id: eth1/49
            -   adminSt: enabled
                id: eth1/57
            -   adminSt: enabled
                id: eth1/8
            -   adminSt: enabled
                id: eth1/53
            -   adminSt: enabled
                id: eth1/113
            -   adminSt: enabled
                id: eth1/68
            -   adminSt: enabled
                id: eth1/6
            -   adminSt: enabled
                id: eth1/20
            -   adminSt: enabled
                id: eth1/84
            -   adminSt: enabled
                id: eth1/123
            -   adminSt: enabled
                id: eth1/109
            -   adminSt: enabled
                id: eth1/58
            -   adminSt: enabled
                id: eth1/4
            -   adminSt: enabled
                id: eth1/73
            -   adminSt: enabled
                id: eth1/34
            -   adminSt: enabled
                id: eth1/60
            -   adminSt: enabled
                id: eth1/112
            -   adminSt: enabled
                id: eth1/66
            -   adminSt: enabled
                id: eth1/24
            -   adminSt: enabled
                id: eth1/89
            -   adminSt: enabled
                id: eth1/97
            -   adminSt: enabled
                id: eth1/36
            -   adminSt: enabled
                id: eth1/102
            -   adminSt: enabled
                id: eth1/121
            -   adminSt: enabled
                id: eth1/44
            -   adminSt: enabled
                id: eth1/12
            -   adminSt: enabled
                id: eth1/59
            -   adminSt: enabled
                id: eth1/119
            -   adminSt: enabled
                id: eth1/17
            -   adminSt: enabled
                id: eth1/21
            -   adminSt: enabled
                id: eth1/31
            -   adminSt: enabled
                id: eth1/32
            -   adminSt: enabled
                id: eth1/14
            -   adminSt: enabled
                id: eth1/108
            -   adminSt: enabled
                id: eth1/101
            -   adminSt: enabled
                id: eth1/13
            -   adminSt: enabled
                id: eth1/64
            -   adminSt: enabled
                id: eth1/125
            -   adminSt: enabled
                id: eth1/47
            -   adminSt: enabled
                id: eth1/54
            -   adminSt: enabled
                id: eth1/19
            -   adminSt: enabled
                id: eth1/87
            -   adminSt: enabled
                id: eth1/77
            -   adminSt: enabled
                id: eth1/1
            -   adminSt: enabled
                id: eth1/126
            -   adminSt: enabled
                id: eth1/104
            -   adminSt: enabled
                id: eth1/3
            -   adminSt: enabled
                id: eth1/98
            -   adminSt: enabled
                id: eth1/82
            -   adminSt: enabled
                id: eth1/29
            -   adminSt: enabled
                id: eth1/28
            -   adminSt: enabled
                id: eth1/80
            -   adminSt: enabled
                id: eth1/116
            -   adminSt: enabled
                id: eth1/9
            -   adminSt: enabled
                id: eth1/35
            -   adminSt: enabled
                id: eth1/118
            -   adminSt: enabled
                id: eth1/120
            -   adminSt: enabled
                id: eth1/93
            -   adminSt: enabled
                id: eth1/85
            -   adminSt: enabled
                id: eth1/94
            -   adminSt: enabled
                id: eth1/39
            -   adminSt: enabled
                id: eth1/48
            -   adminSt: enabled
                id: eth1/83
            -   adminSt: enabled
                id: eth1/92
        txFreq: '60'
        ver: v2
