mgmt-items:
    MgmtIf-list:
        adminSt: up
        autoNeg: 'on'
        duplex: auto
        id: mgmt0
        mtu: '1500'
        rtvrfMbr-items:
            tCl: l3Inst
            tDn: /System/inst-items/Inst-list[mode='management']
        snmpTrapSt: enable
        speed: auto
